### ISSUE TITLE
Character Will

### ISSUE THREAD

**Issue by Tricky1975** [PhantasarProductions/dyrt#70]
These are unique abilities for characters, and they are automatically used when needed, and a special rate for them to be used differs per difficulty

- Young Irravonia
  - [x] None
- Eric
  - [x] Coup-de-grace (When enemy is below certain % of HP, Eric will finish it off) (Rate Easy=10%, Casual=5%, Hard=1%)
- Irravonia
  - [x] Elemental protection (Irravonia can random nullify the effect of either Water, Fire, Wind or Earth) #196
- Brendor
   - [x] Block (Brendor can nullify all damage to 0. Rate Easy=25%, Casual=10%, Hard=2%) #197
- Scyndi
   - [x] Emergency action (When after damage Scyndi or an ally is critically wounded, she'll move to COM immediately, unless she was already moving from COM to ACT. HP% Easy=25%, Casual=20%, Hard=5%) #198
- Rebecca
  - [x] Strike Streak (After a regular attack Rebecca has the change to strike again. Chance lowers in streak. Start rate Easy=40%, Casual=25%, Hard=20%, Dec rate per streak Easy=1%, Casual=5%, Hard=10%) #199
- Dernor
  - [ ] Willpower (If after attack heavily wounded, Dernor may set his AP and HP to max (only AP in hard mode). HP: Easy=30%, Casual=20%, Hard=10%) #200
- Merya
  - [x] Conserve (Merya may use a consumable without consuming it. Rate: Easy: 75%, Casual: 50%, Hard: 25%) #201
- Aziëlla
  - [x] Feint Shot (Aziëlla may shoot an cancel enemy's attacks, if they have targeted her: Rate Easy:66%, Casual: 33%, Hard=11%) #202
  - [x] Accuracy - Aziëlla NEVER misses a shot!

- Queen Shanda
  - [x] Regeneration (As the start of each turn Shanda regenerates HP (Easy: 75%, Casual: 25%, Hard:2%) #206 
- Kirana
  - [x] Magic refuel: Kirana regains extra AP at the start of each turn (Easy:25, Medium:10, Hard:1) #207
